
import { Language } from './types';

export const ORDER_PHONE = "919616921617";

export const TRANSLATIONS = {
  [Language.EN]: {
    appName: "Manish Yadav MedCenter",
    home: "Home",
    explorer: "Medicine Explorer",
    assistant: "Medical Consultant AI",
    orderNav: "Direct Order",
    dashboard: "Health Dashboard",
    reminders: "Smart Reminders",
    order: "Order via WhatsApp",
    searchPlaceholder: "Search medicine name (e.g. Paracetamol)...",
    chatPlaceholder: "Describe your symptoms or ask medical questions...",
    stock: "In Stock",
    outOfStock: "Low Stock",
    addMedicine: "Add Item",
    history: "Medication History",
    usageTrend: "Usage Trends",
    dosage: "Dosage",
    composition: "Composition",
    sideEffects: "Side Effects",
    uses: "Common Uses",
    medName: "Medicine Name",
    totalStock: "Quantity",
    timing: "Notes (Optional)",
    save: "Add Item",
    cancel: "Cancel",
    welcome: "Welcome to MedCenter",
    heroTitle: "Expert Healthcare & AI Diagnostics",
    heroSub: "Access professional medical insights, manage prescriptions, and consult our senior AI consultant at Manish Yadav MedCenter.",
    getStarted: "Start Exploring",
    buyNow: "Order on WhatsApp",
    orderSummary: "Prescription List",
    emptyOrder: "Your order list is empty. Add medicines to order.",
    sendOrder: "Confirm & Send Order",
    address: "Full Delivery Address",
    unitNo: "Flat / House / Unit No.",
    mobileNo: "Contact Number",
    checkoutHeader: "Delivery Details",
    back: "Back to List",
    checkoutNote: "These details will be included in your WhatsApp order message.",
    langSwitchGreeting: "Greetings. I am your Senior Medical Consultant. How may I assist you today?",
    featureExplorerTitle: "Advanced Drug Index",
    featureExplorerDesc: "Get clinical data, pharmacology, and side effects instantly.",
    featureAssistantTitle: "Senior AI Consultant",
    featureAssistantDesc: "Professional medical consultation and symptom analysis 24/7.",
    featureOrderTitle: "Direct Pharmacy",
    featureOrderDesc: "Seamlessly send your medication list to our verified pharmacy channel."
  },
  [Language.HI]: {
    appName: "मनीष यादव मेडसेंटर",
    home: "होम",
    explorer: "मेडिसिन इंडेक्स",
    assistant: "AI चिकित्सा विशेषज्ञ",
    orderNav: "सीधा ऑर्डर",
    dashboard: "हेल्थ डैशबोर्ड",
    reminders: "स्मार्ट रिमाइंडर",
    order: "सीधा ऑर्डर",
    searchPlaceholder: "दवाई का नाम लिखें (जैसे पैरासिटामोल)...",
    chatPlaceholder: "अपने लक्षणों या स्वास्थ्य संबंधी समस्याओं के बारे में पूछें...",
    stock: "स्टॉक में",
    outOfStock: "स्टॉक कम है",
    addMedicine: "दवाई जोड़ें",
    history: "दवाई का इतिहास",
    usageTrend: "उपयोग का ट्रेंड",
    dosage: "खुराक",
    composition: "बनावट/सामग्री",
    sideEffects: "दुष्प्रभाव",
    uses: "प्रमुख उपयोग",
    medName: "दवाई का नाम",
    totalStock: "मात्रा",
    timing: "विशेष नोट (वैकल्पिक)",
    save: "दवाई जोड़ें",
    cancel: "रद्द करें",
    welcome: "मेडसेंटर में आपका स्वागत है",
    heroTitle: "विशेषज्ञ स्वास्थ्य सेवा और AI निदान",
    heroSub: "मनीष यादव मेडसेंटर पर पेशेवर चिकित्सा जानकारी प्राप्त करें, अपनी दवाओं का प्रबंधन करें और हमारे वरिष्ठ AI विशेषज्ञ से परामर्श लें।",
    getStarted: "अभी शुरू करें",
    buyNow: "व्हाट्सएप पर ऑर्डर करें",
    orderSummary: "ऑर्डर की गई दवाएं",
    emptyOrder: "आपकी सूची अभी खाली है। कृपया दवाएं जोड़ें।",
    sendOrder: "पुष्टि करें और ऑर्डर भेजें",
    address: "पूरा डिलीवरी पता",
    unitNo: "फ्लैट / घर / यूनिट नंबर",
    mobileNo: "मोबाइल नंबर",
    checkoutHeader: "डिलीवरी का विवरण",
    back: "सूची पर वापस जाएं",
    checkoutNote: "यह विवरण आपके व्हाट्सएप ऑर्डर मैसेज में शामिल किया जाएगा।",
    langSwitchGreeting: "अभिवादन। मैं आपका वरिष्ठ चिकित्सा सलाहकार (Senior Medical Consultant) हूँ। आज मैं आपकी किस प्रकार सहायता कर सकता हूँ?",
    featureExplorerTitle: "एडवांस मेडिसिन खोज",
    featureExplorerDesc: "किसी भी दवाई के क्लिनिकल डेटा, उपयोग और साइड इफेक्ट्स की पूरी जानकारी पाएं।",
    featureAssistantTitle: "सीनियर AI विशेषज्ञ",
    featureAssistantDesc: "पेशेवर चिकित्सा परामर्श और लक्षणों का विश्लेषण 24/7 उपलब्ध।",
    featureOrderTitle: "डायरेक्ट फार्मेसी",
    featureOrderDesc: "अपनी दवाई की सूची सीधे हमारे सत्यापित फार्मेसी चैनल पर भेजें।"
  }
};

export const INITIAL_ORDER_ITEMS = [
  { id: '1', name: 'Paracetamol 500mg', dosage: '1 Strip', timing: 'SOS', stock: 1, totalStock: 1 },
];
