
import { Language } from './types';

export const ORDER_PHONE = "919616921617";

export const TRANSLATIONS = {
  [Language.EN]: {
    appName: "Manish Yadav Health",
    home: "Home",
    explorer: "Medicine Explorer",
    assistant: "Health Assistant",
    orderNav: "Direct Order",
    dashboard: "Health Dashboard",
    reminders: "Smart Reminders",
    order: "Order via WhatsApp",
    searchPlaceholder: "Search medicine name (e.g. Paracetamol)...",
    chatPlaceholder: "Ask anything about your health...",
    stock: "In Stock",
    outOfStock: "Low Stock",
    addMedicine: "Add Item",
    history: "Medication History",
    usageTrend: "Usage Trends",
    dosage: "Dosage",
    composition: "Composition",
    sideEffects: "Side Effects",
    uses: "Common Uses",
    medName: "Medicine Name",
    totalStock: "Quantity",
    timing: "Notes (Optional)",
    save: "Add Item",
    cancel: "Cancel",
    welcome: "Welcome, User",
    heroTitle: "Premium Healthcare at Your Fingertips",
    heroSub: "Manage your medicines, consult our AI assistant, and track your health progress with Manish Yadav's elite health portal.",
    getStarted: "Explore Features",
    buyNow: "Order on WhatsApp",
    orderSummary: "Your Order List",
    emptyOrder: "Your order list is empty. Add medicines to order.",
    sendOrder: "Confirm & Send Order",
    address: "Full Delivery Address",
    unitNo: "Flat / House / Unit No.",
    mobileNo: "Contact Number",
    checkoutHeader: "Delivery Details",
    back: "Back to List",
    checkoutNote: "These details will be included in your WhatsApp order message.",
    langSwitchGreeting: "Hello! I am now ready to assist you in English.",
    featureExplorerTitle: "AI Medicine Finder",
    featureExplorerDesc: "Get full details including side effects and dosage instantly.",
    featureAssistantTitle: "Personal AI Doc",
    featureAssistantDesc: "Ask any health question and get expert advice 24/7.",
    featureOrderTitle: "Direct Pharmacy",
    featureOrderDesc: "Send your medicine list directly to WhatsApp for delivery."
  },
  [Language.HI]: {
    appName: "मनीष यादव स्वास्थ्य",
    home: "होम",
    explorer: "दवाई खोजक",
    assistant: "AI सहायक",
    orderNav: "सीधा ऑर्डर",
    dashboard: "हेल्थ डैशबोर्ड",
    reminders: "स्मार्ट रिमाइंडर",
    order: "सीधा ऑर्डर",
    searchPlaceholder: "दवाई का नाम लिखें (जैसे पैरासिटामोल)...",
    chatPlaceholder: "अपने स्वास्थ्य के बारे में कुछ भी पूछें...",
    stock: "स्टॉक में",
    outOfStock: "स्टॉक कम है",
    addMedicine: "दवाई जोड़ें",
    history: "दवाई का इतिहास",
    usageTrend: "उपयोग का ट्रेंड",
    dosage: "खुराक",
    composition: "बनावट",
    sideEffects: "दुष्प्रभाव",
    uses: "सामान्य उपयोग",
    medName: "दवाई का नाम",
    totalStock: "मात्रा",
    timing: "नोट (वैकल्पिक)",
    save: "दवाई जोड़ें",
    cancel: "रद्द करें",
    welcome: "स्वागत है, यूज़र",
    heroTitle: "प्रीमियम स्वास्थ्य सेवा अब आपके हाथ में",
    heroSub: "मनीष यादव के इस पोर्टल के साथ अपनी दवाएं प्रबंधित करें, हमारे AI सहायक से परामर्श करें और अपने स्वास्थ्य की प्रगति को ट्रैक करें।",
    getStarted: "सुविधाएं देखें",
    buyNow: "व्हाट्सएप पर ऑर्डर करें",
    orderSummary: "आपकी ऑर्डर सूची",
    emptyOrder: "आपकी ऑर्डर सूची खाली है। ऑर्डर करने के लिए दवाएं जोड़ें।",
    sendOrder: "पुष्टि करें और ऑर्डर भेजें",
    address: "पूरा डिलीवरी पता",
    unitNo: "फ्लैट / घर / यूनिट नंबर",
    mobileNo: "संपर्क नंबर",
    checkoutHeader: "डिलीवरी विवरण",
    back: "सूची पर वापस जाएं",
    checkoutNote: "यह विवरण आपके व्हाट्सएप ऑर्डर संदेश में शामिल किया जाएगा।",
    langSwitchGreeting: "नमस्ते! अब मैं आपकी हिंदी में सहायता करने के लिए तैयार हूँ।",
    featureExplorerTitle: "AI दवाई खोजक",
    featureExplorerDesc: "दुष्प्रभाव और खुराक सहित पूरी जानकारी तुरंत प्राप्त करें।",
    featureAssistantTitle: "पर्सनल AI डॉक्टर",
    featureAssistantDesc: "स्वास्थ्य संबंधी कोई भी प्रश्न पूछें और 24/7 सलाह लें।",
    featureOrderTitle: "सीधी फार्मेसी",
    featureOrderDesc: "डिलीवरी के लिए अपनी दवाई सूची सीधे व्हाट्सएप पर भेजें।"
  }
};

export const INITIAL_ORDER_ITEMS = [
  { id: '1', name: 'Paracetamol 500mg', dosage: '1 Strip', timing: 'Urgent', stock: 1, totalStock: 1 },
];
